version: 0.2

env:
  variables:
    PROJECT: AspNetMvcSampleApp
    DOTNET_FRAMEWORK: 4.6.1
phases:
  build:
    commands:
      - dotnet build
artifacts:
  files:
    - '**/*'
  base-directory: dist/RPSCAPSTONESERVICE
